site_name: SNN_simulator
#site_url: https://salah-daddi-nounou.github.io/snn_simulator/
repo_url: https://salah-daddi-nounou.github.io/snn_simulator
repo_name: snn_simulator
edit_url: ""
theme:
    #logo: 
    name: material
    palette:
        - scheme: default
          toggle:
            icon: material/toggle-switch-off-outline
            name: Switch to dark mode
          primary: black
          accent: light blue
        - scheme: slate
          toggle: 
            icon: material/toggle-switch
            name: Switch to light mode
          primary: white
          accent: dark blue
    font:
        text: Roboto
        code: Roboto Mono
    #icon:
        #repo: 
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.top
        - navigation.sections
        - navigation.expand
        - toc.integrate
        - content.code.annotate

#extra_css:
#  - 
  
plugins:
  - search
#  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_type_hint: true



markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences

nav:
    - Introduction: index.md
    - Netlist generator: net_generator.md
    

