site_name: SNN simulator
site_url: https://salah-daddi-nounou.github.io/               # my user github page 
repo_url: https://github.com/salah-daddi-nounou/snn_simulator # to access repo from docs
repo_name: snn_simulator
# edit_uri: edit/main/docs/            to allow edit the page

theme:
    #logo: img/logo.svg
    name: material
    palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode  

    font:
        text: Roboto
        code: Roboto Mono
    icon:
        repo: fontawesome/brands/github
    features:
        - announce.dismiss
        - content.action.edit
        - content.action.view
        - content.code.annotate
        - content.code.copy
        - content.code.select
        # - content.tabs.link
        - content.tooltips
        # - header.autohide
        # - navigation.expand
        - navigation.footer
        - navigation.indexes
        - navigation.instant
        # - navigation.prune
        - navigation.sections
        - navigation.tabs
        # - navigation.tabs.sticky
        - navigation.top
        - navigation.tracking
        - search.highlight
        - search.share
        - search.suggest
        - toc.follow
        - toc.integrate    

#extra_css:
#  - 
  
plugins:
  - search
#  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_type_hint: true

markdown_extensions:
  - attr_list
  - md_in_html
  - def_list
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - codehilite
  - footnotes
  - meta
  - toc:
      permalink: true

nav:
    - Home: index.md
    - Usage: usage.md 
    - Simulation Workflow: workflow.md 
    - API Refrence: 
      - API: api.md
      - Device Models:
        - Input Neuron: in_neuron.md
        - Output Neuron: out_neuron.md
        - MTJ : mtj_model.md
